### ISSUE TITLE
await repetition

### ISSUE THREAD

**Issue by gngpp** [mikaelmello/inquire#83] opened 2022-12-14 07:33 UTC
question：call function await on match, prompt repeats.
<img width="679" alt="image" src="https://user-images.githubusercontent.com/51810656/207533415-482bdec5-0095-46f2-9ee2-469682c55a5a.png">

code: 
```rust
    const PEER: &str = "peer";
    const PEER_SERVER: &str = "peer-server";
    let node_type_option = vec![PEER, PEER_SERVER];
    let node_type_select = inquire::Select::new("Select the peer node type that needs to be revoked.", node_type_option).prompt();
    match node_type_select {
        Ok(node_type) => {
            match node_type {
                PEER => {
                    let mut configuration = Configuration::new(config).await?;
                    let node_list = configuration.list().await?;
                    let node_option = node_list.iter()
                        .map(|v| v.name())
                        .collect::<Vec<&str>>();
                    let node_select = inquire::Select::new("Select node", node_option).prompt();
                    match node_select {
                        Ok(choice) => {
                            println!("{}", choice);
                        }
                        Err(_) => {}
                    }
                }
                PEER_SERVER => {
                    println!("{}", PEER_SERVER);
                }
                _ => {}
            }
        },

        Err(_) => {
            println!("There was an error, please try again")
        }
    }
    Ok(())
```

**Comment by gngpp** [comment] 2022-12-14 13:20
> This problem arises whenever asynchronous function calls are made before inquire::Select instances
```rust
pub(crate) async fn subcommand_print_peer_handler(_config: String) -> anyhow::Result<()> {
    let mut configuration = <Configuration as AsyncTryFrom<String>>::try_from(_config).await?;

    let node_type_select = inquire::Select::new(
        "Select the node configuration to print",
        vec![PEER_TYPE, PEER_SERVER_TYPE],
    )
    .prompt();

    match node_type_select {
        Ok(node_type) => {
            match node_type {
                PEER_TYPE => {
                    let node_list = configuration.list().await?;
                    let mut node_option = node_list.iter().map(|v| v.name()).collect::<Vec<&str>>();
                    node_option.sort();

                    let option = inquire::Select::new("select peer", node_option)
                        .with_help_message(
                            "This will print the configuration and generate the QR code",
                        )
                        .prompt();
                    match option {
                        Ok(node_name) => {
                            let string = configuration.peer_str(node_name).await?;
                            println!("generated configuration:\n{}\n", string);
                            qr2term::print_qr(string)
                                .context("Failed to generate QRCode configuration")?;
                        }
                        Err(_) => {}
                    }
                }
                PEER_SERVER_TYPE => {
                    let string = configuration.peer_server_str().await?;
                    println!("{}", string);
                }
                _ => {
                    println!("Unable to find matching node type")
                }
            }
            drop(configuration);
        }
        Err(_) => {
            println!("please try again")
        }
    }
    Ok(())
}
```

**Comment by mikaelmello** [comment] 2022-12-14 16:55
Hey! I haven't taken a deep look yet, but would it possible to write me a sample that I could reproduce locally?

I'll try to work on it this weekend

**Comment by gngpp** [comment] 2022-12-15 07:40
> Hey! I haven't taken a deep look yet, but would it possible to write me a sample that I could reproduce locally?
> 
> I'll try to work on it this weekend

```shell
> git clone https://github.com/gngpp/wgsdc.git && wgsdc
> cargo run --example demo
```

> The problem found so far: the sudo library is used: sudo::escalate_if_needed().unwrap() is used to obtain the system sudo permission

**Comment by gngpp** [comment] 2022-12-15 07:46
> > Hey! I haven't taken a deep look yet, but would it possible to write me a sample that I could reproduce locally?
> > I'll try to work on it this weekend
> 
> ```shell
> > git clone https://github.com/gngpp/wgsdc.git && wgsdc
> > cargo run --example demo
> ```
> 
> > The problem found so far: the sudo library is used: sudo::escalate_if_needed().unwrap() is used to obtain the system sudo permission

> Using inquire and https://crates.io/crates/sudo at the same time may cause the above repeated prompts

**Comment by mikaelmello** [comment] 2022-12-19 22:58
I did some digging and I'm afraid there isn't anything inquire can do to avoid that.

When `escalate_if_needed` is called, the `sudo` crate seems to be restarting the entire program to get into a privileged state. So the prompts you make before requesting sudo will be inevitably executed again.

Executing `sudo::escalate_if_needed()` in the beginning of the program should fix the issue you're having.

**Closed by mikaelmello** 2022-12-19 22:58 UTC
Labels: enhancement

**Comment by gngpp** [comment] 2022-12-20 06:52
> I did some digging and I'm afraid there isn't anything inquire can do to avoid that.
> 
> When `escalate_if_needed` is called, the `sudo` crate seems to be restarting the entire program to get into a privileged state. So the prompts you make before requesting sudo will be inevitably executed again.
> 
> Executing `sudo::escalate_if_needed()` in the beginning of the program should fix the issue you're having.

That's all. Thank you very much for your reply
